name = "kairos-weather"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[env.production]
routes = [
  { pattern = "kairos.gr", custom_domain = true },
  { pattern = "www.kairos.gr", custom_domain = true }
]